# config.yaml
# Paths to input files for the pipeline

# Input VCF containing variants of interest
vcf: "/data/humangen_kircherlab/Projects/Model_MPRA_Benchmark/Enformer/Pipeline/Data/VCF/IGVFFI4134MFLL.vcf.gz"
  #  "/data/humangen_kircherlab/Projects/Model_MPRA_Benchmark/Enformer/Pipeline/Data/VCF/IGVFFI4378PZYI.vcf.gz"

# Reference genome and Enformer targets file
fasta: "/data/humangen_kircherlab/Projects/Model_MPRA_Benchmark/Enformer/Pipeline/Data/Genome/hg38.fa"
targets: "/data/humangen_kircherlab/Projects/Model_MPRA_Benchmark/Enformer/Pipeline/Data/Targets/targets_human.txt"

# Experimental MPRA data
# mpra_data: "/data/humangen_kircherlab/Projects/Model_MPRA_Benchmark/Enformer/Pipeline/Data/MPRA/HEPG2_reporter_variants.tsv.gz"
mpra_data: "/data/humangen_kircherlab/Projects/Model_MPRA_Benchmark/Enformer/Pipeline/Data/MPRA/HEK293T_reporter_variants.tsv.gz"

cell_line: "HepG2"
cell_line_column_name: "HepG2"
  #  "Model_MPRA_Benchmark/Enformer/Pipeline/Data/MPRA/HEK293T_reporter_variants.tsv.gz"

# Enformer Variables
max_variants: "1000"  # Maximum number of variants to process (for testing purposes)

# Aggregation flags (set to true to compute the corresponding aggregation during merge)
agg_global: true
agg_global_max: false
agg_global_min: false

agg_per_biosample: false
agg_per_biosample_max: false
agg_per_biosample_min: false

agg_per_assay: true
agg_per_assay_max: false
agg_per_assay_min: false

# Optional: exclude a small symmetric or asymmetric range of mean SAD values from plots
# Set to null to disable, or provide numeric values.
exclude_min:  "None"
exclude_max:  "None"